name: Benchmark

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run benchmarks on current branch
        run: go test -run='^$' -bench=. -count=20 ./drisl > current_bench.txt

      - name: Get base branch benchmarks
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}
          go test -run='^$' -bench=. -count=20 ./drisl > base_bench.txt
          git checkout ${{ github.event.pull_request.head.sha }}

      - name: Compare benchmarks with benchstat
        run: |
          echo "## Benchmark Results" > benchmark_report.md
          echo "" >> benchmark_report.md
          echo "### Performance Regression Analysis" >> benchmark_report.md
          echo '```' >> benchmark_report.md
          benchstat base_bench.txt current_bench.txt >> benchmark_report.md || echo "No significant differences found" >> benchmark_report.md
          echo '```' >> benchmark_report.md

      - name: Comment PR with benchmark results
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: benchmark_report.md

