name: "Lint"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
    - run: "go vet ./..."
